#ifndef SDK_LEVELLOADINGPROGRESS_HPP
#define SDK_LEVELLOADINGPROGRESS_HPP

#include "../Util/Cenum.hpp"

MAKE_CENUM_Q(LevelLoadingProgress_e, int,
	PROGRESS_INVALID, -2,
	PROGRESS_DEFAULT, -1,
	PROGRESS_NONE, 0,
	PROGRESS_CHANGELEVEL, 1,
	PROGRESS_SPAWNSERVER, 2,
	PROGRESS_LOADWORLDMODEL, 3,
	PROGRESS_CRCMAP, 4,
	PROGRESS_CRCCLIENTDLL, 5,
	PROGRESS_CREATENETWORKSTRINGTABLES, 6,
	PROGRESS_PRECACHEWORLD, 7,
	PROGRESS_CLEARWORLD, 8,
	PROGRESS_LEVELINIT, 9,
	PROGRESS_PRECACHE, 10,
	PROGRESS_ACTIVATESERVER, 11,
	PROGRESS_BEGINCONNECT, 12,
	PROGRESS_SIGNONCHALLENGE, 13,
	PROGRESS_SIGNONCONNECT, 14,
	PROGRESS_SIGNONCONNECTED, 15,
	PROGRESS_PROCESSSERVERINFO, 16,
	PROGRESS_PROCESSSTRINGTABLE, 17,
	PROGRESS_SIGNONNEW, 18,
	PROGRESS_SENDCLIENTINFO, 19,
	PROGRESS_SENDSIGNONDATA, 20,
	PROGRESS_SIGNONSPAWN, 21,
	PROGRESS_CREATEENTITIES, 22,
	PROGRESS_FULLYCONNECTED, 23,
	PROGRESS_PRECACHELIGHTING, 24,
	PROGRESS_READYTOPLAY, 25,
	PROGRESS_HIGHESTITEM, 26,
);

#endif // SDK_LEVELLOADINGPROGRESS_HPP
